### ISSUE TITLE
Issue after upgrading react-admin to 3.0.0

### ISSUE THREAD

**Issue by mrdntgrn** [FusionWorks/react-admin-nestjsx-crud-dataprovider#15]
Hi ,

We have NestJs backend Crud and react-admin installed. And we use your awesome Data provider(thanks for sharing it).  

Few days ago I have upgraded to react-admin to 3.0.0 and had issue related to filtration compose appeared. As I understood the issue is related to one to may relation request compose when the lib gets filter by calling composeFilter() function.
All our one-to-many relation related dropdown become broken. As I understood it is related to case when no filtration passed but somehow the lib generates not complete one(something like some-route-to-resource/?filter=q||cont) 

I have done quick fix for it and hope you will approve Pull Request:
https://github.com/FusionWorks/react-admin-nestjsx-crud-dataprovider/pull/14

PS:
Also As I read react-admin have new recommended structure for each Crud request type. Although the legacy function is supported yet I hope someone soon can take care and refactor the current functions implementation to objects:
https://marmelab.com/react-admin/DataProviders.html
![Screen Shot 2019-11-26 at 12 14 26 PM](https://user-images.githubusercontent.com/31103575/69611148-9dd5a180-1046-11ea-9f56-da4bac8d4a88.png)

Thank you

**Comment by gganebnyi** [comment]
@mrdntgrn thanks for pointing this out and providing a fix. We will check it ASAP and merge if all is ok.

**Comment by mrdntgrn** [comment]
Thank you for approval,
I'm closing the issue
